### ISSUE TITLE
how to configure the datas?

### ISSUE THREAD

**Issue by luismauriz1** [steand/optolink#12]
Hey Guys, i Want to integrate my vitoligno 300-P. Could You give ne furhter Steps, how to configure the Optolink ? Could i use one Pi for the Server and another for the Optolink? Or ist that only working locally? How Do i have to Install that Stuff?
Thanks for your answers.

**Comment by Hotte37** [comment]
Hello, yes you can use one Pi for the Server and another for the Optolink. I also have this configuration. I use one RPi for Openhab and one BananaPi (i had it available) at my heater with this Optolink server on it. The Optolink Hardware is connected to the BananaPi at the Heater. 
Openhab communicates with the Optolink Server via network. So Openhab and Optolink server might be on the same hardware, but don't have to. 

I don't have a vitologno, so i cannot help with that.

**Comment by luismauriz1** [comment]
Hi, OK thanks! Could You Tell meine how to configure the Optolink? The specificated vitoligno is for myself easy to do. Gut how Do i have to Install the Optolink?
Kindest Greets
Luismauriz1
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 13.03.18, 11:35, Hotte37 <notifications@github.com> schrieb:
Hello, yes you can use one Pi for the Server and another for the Optolink. I also have this configuration. I use one RPi for Openhab and one BananaPi (i had it available) at my heater with this Optolink server on it. The Optolink Hardware is connected to the BananaPi at the Heater.
Openhab communicates with the Optolink Server via network. So Openhab and Optolink server might be on the same hardware, but don't have to.
I don't have a vitologno, so i cannot help with that.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/steand/optolink","title":"steand/optolink","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/steand/optolink"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Hotte37 in #12: Hello, yes you can use one Pi for the Server and another for the Optolink. I also have this configuration. I use one RPi for Openhab and one BananaPi (i had it available) at my heater with this Optolink server on it. The Optolink Hardware is connected to the BananaPi at the Heater. \r\nOpenhab communicates with the Optolink Server via network. So Openhab and Optolink server might be on the same hardware, but don't have to. \r\n\r\nI don't have a vitologno, so i cannot help with that.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/steand/optolink/issues/12#issuecomment-372620272"}}}

**Comment by Hotte37** [comment]
I followed the instruction of the readme:
I extracted the "optolink-bin-1.0.0-RC1.zip" into the /opt folder, modified the /opt/optolink/conf/optolink.xml and started it with /opt/optolink/start.sh.
If this works, then but a init-script into init.d. Thats all.
Of course you need java installed on the Pi.

**Comment by luismauriz1** [comment]
Ok. Thanks. Now i downloaded and copied the file. but how is the start command? `root@raspberrypi:/opto/optolink-master/src/main/resources# sudo ./start.sh
sudo: unable to execute ./start.sh: No such file or directory
` is something wrong? The cmod is done already. But it won`t start. Thanks for your great help!

**Comment by Hotte37** [comment]
You downloaded the wrong file. You have to download the bin file and not the source file.

**Comment by luismauriz1** [comment]
Oohh. And where ist the right File? I cant find the Download Button ;)

Hotte37 <notifications@github.com> schrieb am Di., 13. März 2018, 23:52:

**Comment by Hotte37** [comment]
You have to klick on "releases". There you find the bin file.

**Comment by luismauriz1** [comment]
Oohh i found that. I'm so stupid. Thanks! I will try that!

Hotte37 <notifications@github.com> schrieb am Mi., 14. März 2018, 07:10:

**Comment by luismauriz1** [comment]
Soooo, i have installed the programm correctly. and it shows me 

`Optolink adapter started
`
So i think that is is started correctly. i configured the optolink.xml with my /dev/ttyUSB0.
now, Openhab wants to know the adapter id. But where can i find her?
Or what should i fill in ?
Thanks for your answers!

**Comment by Hotte37** [comment]
Look into the optolink.xml.

**Comment by steand** [comment]
For test the adapter maybe this helps:
https://github.com/steand/optolink/wiki/Build-Install-Run
Be sure that you have no connection from OH.

**Comment by luismauriz1** [comment]
My problem is the following:
`./start_debug.sh
11:10:54.867 [main] INFO  de.myandres.optolink.Main main - Programm gestartet
11:10:54.886 [main] DEBUG de.myandres.optolink.Config <init> - Try to open File conf/optolink.xml
11:10:54.892 [main] INFO  de.myandres.optolink.Config <init> - File conf/optolink.xml open for parsing
11:10:54.895 [main] DEBUG de.myandres.optolink.Config <init> - Start parsing
11:10:54.903 [main] INFO  de.myandres.optolink.Config setAdapterID - Set adapterID: VITOLIGNO
11:10:54.904 [main] INFO  de.myandres.optolink.Config setTTY - Set tty: /dev/ttyUSB0
11:10:54.906 [main] INFO  de.myandres.optolink.Config setTtyTimeOut - Set TTY Timeout: 2000 Milliseconds
11:10:54.907 [main] INFO  de.myandres.optolink.Config setPort - Set Socket Port: 31113
11:10:54.921 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.923 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.928 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.935 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.936 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.939 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.941 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.942 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.944 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.945 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.947 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.948 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.950 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.952 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.954 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.957 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.958 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.959 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.961 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.962 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.963 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.965 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.968 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.969 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.970 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.972 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
11:10:54.973 [main] INFO  de.myandres.optolink.Config <init> - 6 Things are parsed
11:10:54.976 [main] DEBUG d.m.optolink.OptolinkInterface <init> - Open TTY /dev/ttyUSB0 ...
java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while loading gnu.io.RXTXCommDriver
Exception in thread "main" java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:83)
        at de.myandres.optolink.OptolinkInterface.<init>(OptolinkInterface.java:44)
        at de.myandres.optolink.Main.main(Main.java:39)
root@raspberrypi:/opto/optolink#
`

i dont know, what i could change. when i try to log in with putty and RAW it shows me "Connection Refused"

**Comment by Hotte37** [comment]
Did you use the original optolink-bin-1.0.0-RC1.zip?
Accoding to this, it seems that the application cannot find the rxtx-Library, but this is insode the JAR-File.
> Open TTY /dev/ttyUSB0 .. java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while loading

**Comment by luismauriz1** [comment]
the ttyUSB0 file is empty. what should i fill into them?

**Comment by luismauriz1** [comment]
yes i have the origin zip.

**Comment by Hotte37** [comment]
Have you installed the rxtx package (apt-get install rxtx)?
You can check if it is installed with "apt list --installed | grep rxtx".

**Comment by steand** [comment]
@luismauriz1 you are the same person as on my PM?

**Comment by luismauriz1** [comment]
Yes ;)
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 18.03.18, 13:33, Stefan Andres <notifications@github.com> schrieb:
@luismauriz1 you are the same person as on my PM?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/steand/optolink","title":"steand/optolink","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/steand/optolink"}},"updates":{"snippets":[{"icon":"PERSON","message":"@steand in #12: @luismauriz1 you are the same person as on my PM?"}],"action":{"name":"View Issue","url":"https://github.com/steand/optolink/issues/12#issuecomment-373994937"}}}

**Comment by luismauriz1** [comment]
Hello again,
I have currently a problem with 3 things, the Outside temp and 2 others don´t show me a value. i get the following error code 

> 15:52:14.622 [Thread-93] ERROR de.myandres.optolink.SocketHandler getThing - Channel : pelletburner.error not define! 
15:52:15.764 [Thread-94] ERROR de.myandres.optolink.SocketHandler getThing - Channel : 300P.outside_temp not define! 
15:52:15.829 [Thread-94] ERROR de.myandres.optolink.SocketHandler getThing - Channel : 300P.flowuprating not define! 
thanks for your help
