### ISSUE TITLE
Can't use socat virtual port

### ISSUE THREAD

**Issue by Fejitatete** [steand/optolink#17]
Hi,

I use with success a serial->telnet bridge to control my boiler with vcontrold. With your adapter, as it use only serial, I created a virtual port with socat : 
`socat -d -d pty,link=/dev/ttyAMA0,raw,echo=0,waitslave tcp:192.168.0.4:23;`

but I have the following error message : 

```
00:04:05.223 [main] DEBUG d.m.optolink.OptolinkInterface <init> - Open TTY /dev/ttyAMA0 ...
Stable Library
=========================================
Native lib Version = RXTX-2.2pre2
Java lib Version   = RXTX-2.1-7
WARNING:  RXTX Version mismatch
        Jar version = RXTX-2.1-7
        native lib Version = RXTX-2.2pre2
RXTX Warning:  Removing stale lock file. /var/lock/lockdev/LCK..ttyAMA0
00:04:05.367 [main] ERROR de.myandres.optolink.Main main - Something is wrong not init
gnu.io.UnsupportedCommOperationException: Invalid Parameter
        at gnu.io.RXTXPort.setSerialPortParams(RXTXPort.java:171) ~[optolink-jar-with-dependencies.jar:na]
        at de.myandres.optolink.OptolinkInterface.<init>(OptolinkInterface.java:53) ~[optolink-jar-with-dependencies.jar:na]
        at de.myandres.optolink.Main.main(Main.java:39) ~[optolink-jar-with-dependencies.jar:na]
Exception in thread "main" java.lang.NullPointerException
        at de.myandres.optolink.Main.main(Main.java:46)
```

Could you help me with this or add the possibility to use a net port for data ?
Thx.
Regards,
Feji.

**Comment by Fejitatete** [comment]
Sry, I didn't see commits. Problem solved.
