### ISSUE TITLE
Problem with Reinstallation of The Adapter

### ISSUE THREAD

**Issue by luismauriz1** [steand/optolink#18]
Hello, it's me again ;)
I'd tried to reinstall my Adapter System but when I try to start the Adapter with Start_debug then I got an error:

` Native lib Version = RXTX-2.2pre2
Java lib Version   = RXTX-2.1-7
WARNING:  RXTX Version mismatch
        Jar version = RXTX-2.1-7
        native lib Version = RXTX-2.2pre2
22:19:40.704 [main] ERROR de.myandres.optolink.Main main - Something is wrong not init
gnu.io.NoSuchPortException: null
        at gnu.io.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:218) ~[optolink-jar-with-dependencies.jar:na]
        at de.myandres.optolink.OptolinkInterface.<init>(OptolinkInterface.java:52) ~[optolink-jar-with-dependencies.jar:na]
        at de.myandres.optolink.Main.main(Main.java:39) ~[optolink-jar-with-dependencies.jar:na]
Exception in thread "main" java.lang.NullPointerException
        at de.myandres.optolink.Main.main(Main.java:46) `

So my RXTX Libary is not the Correct.
In your Build Run Install is the only comment " Install rxtx (apt-get)
I tried the sudo apt-get install librxtx-java to install that. But are there more Packages to get the System working?

I want to Create a complete Installation Guide, how to install the Complete System on your Rpi.
Because for me as an beginner is the Complete Process quite complicated...
So I want to help other People to get this thing working.. Is it possible that I write a complete Wiki Entry with the install.

**Comment by steand** [comment]
Hello,

My system runs a long time and i didn't reinstall it.
But I remember that we had the same problem described in: https://github.com/steand/optolink/issues/4
I hope it helps

Regards
Stefan

**Comment by luismauriz1** [comment]
Hello,
OK, I solved this problem. 
But I have another problem with the System.
About every 2 or 3 days, the System is starting bugging. In OH the Things are Online but I can't see any Values. At every Item I see a "0". 
In my directionory, I get a NEW data who is called Optolink.pid.
Everytime, when I remove this data, the system is working after a reboot.
In the Optolink.pid is only one line : "13707".
Thats it.
I hope you can help me :)
