### ISSUE TITLE
NoSuchPortException

### ISSUE THREAD

**Issue by dominikbenner** [steand/optolink#7]
Hi! Ich habe das Problem, dass mein USB Port nicht erkannt wird..

lrwxrwxrwx  1 root     root            7 Jul 13 11:36 ViessmannOptolink -> ttyUSB2

auch /dev/ttyUSB2 bringt dieselbe Meldung.

```
[13:28:44] openhabian@openhabian:/etc/openhab2/scripts/optolink$ sudo ./start_trace.sh
13:29:03.862 [main] INFO  de.myandres.optolink.Main main - Programm gestartet
13:29:04.335 [main] DEBUG de.myandres.optolink.Config <init> - Try to open File conf/optolink.xml
13:29:04.606 [main] INFO  de.myandres.optolink.Config <init> - File conf/optolink.xml open for parsing
13:29:04.659 [main] DEBUG de.myandres.optolink.Config <init> - Start parsing
13:29:04.715 [main] INFO  de.myandres.optolink.Config setAdapterID - Set adapterID: VITOCAL
13:29:04.740 [main] INFO  de.myandres.optolink.Config setTTY - Set tty: /dev/ViessmannOptolink
13:29:04.770 [main] INFO  de.myandres.optolink.Config setTtyTimeOut - Set TTY Timeout: 2000 Milliseconds
13:29:04.786 [main] INFO  de.myandres.optolink.Config setPort - Set Socket Port: 31113
13:29:04.848 [main] TRACE de.myandres.optolink.Thing <init> - Init type: 'heating' id: 'Vitocal'
13:29:04.887 [main] TRACE de.myandres.optolink.Channel <init> - Init id: 'systemtime'
13:29:04.936 [main] TRACE de.myandres.optolink.Telegram setAddress - ----------------------------------------
13:29:04.968 [main] TRACE de.myandres.optolink.Telegram setAddress - Set Adress to 1680(5760)
13:29:05.070 [main] TRACE de.myandres.optolink.Telegram setType - Set Type to short(4) length=2
13:29:05.101 [main] DEBUG de.myandres.optolink.Telegram setDivider - divider not set - set to default: 1
13:29:05.122 [main] TRACE de.myandres.optolink.Telegram setDivider - Set dividerider to 1
13:29:05.146 [main] TRACE de.myandres.optolink.Channel <init> - Init id: 'systemtime'
13:29:05.167 [main] TRACE de.myandres.optolink.Config addThing - Add thing id: Vitocal
13:29:05.194 [main] TRACE de.myandres.optolink.Thing <init> - Init type: 'heating' id: 'Vitocal'
13:29:05.217 [main] INFO  de.myandres.optolink.Config <init> - 1 Things are parsed
13:29:05.262 [main] DEBUG d.m.optolink.OptolinkInterface <init> - Open TTY /dev/ViessmannOptolink ...
Stable Library
=========================================
Native lib Version = RXTX-2.2pre2
Java lib Version   = RXTX-2.1-7
WARNING:  RXTX Version mismatch
        Jar version = RXTX-2.1-7
        native lib Version = RXTX-2.2pre2
13:29:06.178 [main] ERROR de.myandres.optolink.Main main - Something is wrong not init
gnu.io.NoSuchPortException: null
        at gnu.io.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:218) ~[optolink-jar-with-dependencies.jar:na]
        at de.myandres.optolink.OptolinkInterface.<init>(OptolinkInterface.java:44) ~[optolink-jar-with-dependencies.jar:na]
        at de.myandres.optolink.Main.main(Main.java:39) ~[optolink-jar-with-dependencies.jar:na]
Exception in thread "main" java.lang.NullPointerException
        at de.myandres.optolink.Main.main(Main.java:46)
```

**Comment by dominikbenner** [comment]
BTW: Läuft das Programm auch unter Windows?

**Comment by dominikbenner** [comment]
Hab die Lösung selbst gefunden:
In den Java Args wird ein fester Port übergeben. Der überschreibt den in der config nehme ich an.

**Comment by steand** [comment]
Mit dem Port ist es so, dass im Startscript start*.sh der Port angegeben werden muss (sonst wird er von der library nicht gefunden).
Er muss identisch mit dem in der config (optolink.xml) sein. 
Der Java-Code müsste eigentlich auch unter Windows laufen. 
Das Ansteuern des Adampters müsste man testen, aber nach meiner Denke müsste es auch gehen.
Ein ToDo wäre start*.bat zu schreiben.
